[node.validator00]
use_legacy_p2p = true
persistent_peers = ["seed01"]
[node.validator01]
use_legacy_p2p = true
persistent_peers = ["seed01"]
[node.validator02]
use_legacy_p2p = true
persistent_peers = ["seed01"]
[node.validator03]
use_legacy_p2p = true
persistent_peers = ["seed01"]
[node.seed01]
use_legacy_p2p = true
