[node.seed0]
mode= "seed"
[node.seed1]
mode= "seed"
[node.seed2]
mode= "seed"
[node.seed3]
mode= "seed"
[node.seed4]
mode= "seed"

[node.full00]
mode ="full"
persistent_peers = ["seed0"]
[node.full01]
mode ="full"
persistent_peers = ["seed1"]
[node.full02]
mode ="full"
persistent_peers = ["seed2"]
[node.full03]
mode ="full"
persistent_peers = ["seed3"]
[node.full04]
mode ="full"
persistent_peers = ["seed4"]
[node.full05]
mode ="full"
persistent_peers = ["seed0"]
[node.full06]
mode ="full"
persistent_peers = ["seed1"]
[node.full07]
mode ="full"
persistent_peers = ["seed2"]
[node.full08]
mode ="full"
persistent_peers = ["seed3"]
[node.full09]
mode ="full"
persistent_peers = ["seed4"]
[node.full10]
mode ="full"
persistent_peers = ["seed0"]
[node.full11]
mode ="full"
persistent_peers = ["seed1"]
[node.full12]
mode ="full"
persistent_peers = ["seed2"]
[node.full13]
mode ="full"
persistent_peers = ["seed3"]
[node.full14]
mode ="full"
persistent_peers = ["seed4"]
[node.full15]
mode ="full"
persistent_peers = ["seed0"]
[node.full16]
mode ="full"
persistent_peers = ["seed1"]
[node.full17]
mode ="full"
persistent_peers = ["seed2"]
[node.full18]
mode ="full"
persistent_peers = ["seed3"]
[node.full19]
mode ="full"
persistent_peers = ["seed4"]

[node.validator000]
persistent_peers = ["seed0"]
[node.validator001]
persistent_peers = ["seed1"]
[node.validator002]
persistent_peers = ["seed2"]
[node.validator003]
persistent_peers = ["seed3"]
[node.validator004]
persistent_peers = ["seed4"]
[node.validator005]
persistent_peers = ["seed0"]
[node.validator006]
persistent_peers = ["seed1"]
[node.validator007]
persistent_peers = ["seed2"]
[node.validator008]
persistent_peers = ["seed3"]
[node.validator009]
persistent_peers = ["seed4"]
[node.validator010]
persistent_peers = ["seed0"]
[node.validator011]
persistent_peers = ["seed1"]
[node.validator012]
persistent_peers = ["seed2"]
[node.validator013]
persistent_peers = ["seed3"]
[node.validator014]
persistent_peers = ["seed4"]
[node.validator015]
persistent_peers = ["seed0"]
[node.validator016]
persistent_peers = ["seed1"]
[node.validator017]
persistent_peers = ["seed2"]
[node.validator018]
persistent_peers = ["seed3"]
[node.validator019]
persistent_peers = ["seed4"]
[node.validator020]
persistent_peers = ["seed0"]
[node.validator021]
persistent_peers = ["seed1"]
[node.validator022]
persistent_peers = ["seed2"]
[node.validator023]
persistent_peers = ["seed3"]
[node.validator024]
persistent_peers = ["seed4"]
[node.validator025]
persistent_peers = ["seed0"]
[node.validator026]
persistent_peers = ["seed1"]
[node.validator027]
persistent_peers = ["seed2"]
[node.validator028]
persistent_peers = ["seed3"]
[node.validator029]
persistent_peers = ["seed4"]
[node.validator030]
persistent_peers = ["seed0"]
[node.validator031]
persistent_peers = ["seed1"]
[node.validator032]
persistent_peers = ["seed2"]
[node.validator033]
persistent_peers = ["seed3"]
[node.validator034]
persistent_peers = ["seed4"]
[node.validator035]
persistent_peers = ["seed0"]
[node.validator036]
persistent_peers = ["seed1"]
[node.validator037]
persistent_peers = ["seed2"]
[node.validator038]
persistent_peers = ["seed3"]
[node.validator039]
persistent_peers = ["seed4"]
[node.validator040]
persistent_peers = ["seed0"]
[node.validator041]
persistent_peers = ["seed1"]
[node.validator042]
persistent_peers = ["seed2"]
[node.validator043]
persistent_peers = ["seed3"]
[node.validator044]
persistent_peers = ["seed4"]
[node.validator045]
persistent_peers = ["seed0"]
[node.validator046]
persistent_peers = ["seed1"]
[node.validator047]
persistent_peers = ["seed2"]
[node.validator048]
persistent_peers = ["seed3"]
[node.validator049]
persistent_peers = ["seed4"]
[node.validator050]
persistent_peers = ["seed0"]
[node.validator051]
persistent_peers = ["seed1"]
[node.validator052]
persistent_peers = ["seed2"]
[node.validator053]
persistent_peers = ["seed3"]
[node.validator054]
persistent_peers = ["seed4"]
[node.validator055]
persistent_peers = ["seed0"]
[node.validator056]
persistent_peers = ["seed1"]
[node.validator057]
persistent_peers = ["seed2"]
[node.validator058]
persistent_peers = ["seed3"]
[node.validator059]
persistent_peers = ["seed4"]
[node.validator060]
persistent_peers = ["seed0"]
[node.validator061]
persistent_peers = ["seed1"]
[node.validator062]
persistent_peers = ["seed2"]
[node.validator063]
persistent_peers = ["seed3"]
[node.validator064]
persistent_peers = ["seed4"]
[node.validator065]
persistent_peers = ["seed0"]
[node.validator066]
persistent_peers = ["seed1"]
[node.validator067]
persistent_peers = ["seed2"]
[node.validator068]
persistent_peers = ["seed3"]
[node.validator069]
persistent_peers = ["seed4"]
[node.validator070]
persistent_peers = ["seed0"]
[node.validator071]
persistent_peers = ["seed1"]
[node.validator072]
persistent_peers = ["seed2"]
[node.validator073]
persistent_peers = ["seed3"]
[node.validator074]
persistent_peers = ["seed4"]
[node.validator075]
persistent_peers = ["seed0"]
[node.validator076]
persistent_peers = ["seed1"]
[node.validator077]
persistent_peers = ["seed2"]
[node.validator078]
persistent_peers = ["seed3"]
[node.validator079]
persistent_peers = ["seed4"]
[node.validator080]
persistent_peers = ["seed0"]
[node.validator081]
persistent_peers = ["seed1"]
[node.validator082]
persistent_peers = ["seed2"]
[node.validator083]
persistent_peers = ["seed3"]
[node.validator084]
persistent_peers = ["seed4"]
[node.validator085]
persistent_peers = ["seed0"]
[node.validator086]
persistent_peers = ["seed1"]
[node.validator087]
persistent_peers = ["seed2"]
[node.validator088]
persistent_peers = ["seed3"]
[node.validator089]
persistent_peers = ["seed4"]
[node.validator090]
persistent_peers = ["seed0"]
[node.validator091]
persistent_peers = ["seed1"]
[node.validator092]
persistent_peers = ["seed2"]
[node.validator093]
persistent_peers = ["seed3"]
[node.validator094]
persistent_peers = ["seed4"]
[node.validator095]
persistent_peers = ["seed0"]
[node.validator096]
persistent_peers = ["seed1"]
[node.validator097]
persistent_peers = ["seed2"]
[node.validator098]
persistent_peers = ["seed3"]
[node.validator099]
persistent_peers = ["seed4"]
[node.validator100]
persistent_peers = ["seed0"]
[node.validator101]
persistent_peers = ["seed1"]
[node.validator102]
persistent_peers = ["seed2"]
[node.validator103]
persistent_peers = ["seed3"]
[node.validator104]
persistent_peers = ["seed4"]
[node.validator105]
persistent_peers = ["seed0"]
[node.validator106]
persistent_peers = ["seed1"]
[node.validator107]
persistent_peers = ["seed2"]
[node.validator108]
persistent_peers = ["seed3"]
[node.validator109]
persistent_peers = ["seed4"]
[node.validator110]
persistent_peers = ["seed0"]
[node.validator111]
persistent_peers = ["seed1"]
[node.validator112]
persistent_peers = ["seed2"]
[node.validator113]
persistent_peers = ["seed3"]
[node.validator114]
persistent_peers = ["seed4"]
[node.validator115]
persistent_peers = ["seed0"]
[node.validator116]
persistent_peers = ["seed1"]
[node.validator117]
persistent_peers = ["seed2"]
[node.validator118]
persistent_peers = ["seed3"]
[node.validator119]
persistent_peers = ["seed4"]
[node.validator120]
persistent_peers = ["seed0"]
[node.validator121]
persistent_peers = ["seed1"]
[node.validator122]
persistent_peers = ["seed2"]
[node.validator123]
persistent_peers = ["seed3"]
[node.validator124]
persistent_peers = ["seed4"]
[node.validator125]
persistent_peers = ["seed0"]
[node.validator126]
persistent_peers = ["seed1"]
[node.validator127]
persistent_peers = ["seed2"]
[node.validator128]
persistent_peers = ["seed3"]
[node.validator129]
persistent_peers = ["seed4"]
[node.validator130]
persistent_peers = ["seed0"]
[node.validator131]
persistent_peers = ["seed1"]
[node.validator132]
persistent_peers = ["seed2"]
[node.validator133]
persistent_peers = ["seed3"]
[node.validator134]
persistent_peers = ["seed4"]
[node.validator135]
persistent_peers = ["seed0"]
[node.validator136]
persistent_peers = ["seed1"]
[node.validator137]
persistent_peers = ["seed2"]
[node.validator138]
persistent_peers = ["seed3"]
[node.validator139]
persistent_peers = ["seed4"]
[node.validator140]
persistent_peers = ["seed0"]
[node.validator141]
persistent_peers = ["seed1"]
[node.validator142]
persistent_peers = ["seed2"]
[node.validator143]
persistent_peers = ["seed3"]
[node.validator144]
persistent_peers = ["seed4"]
[node.validator145]
persistent_peers = ["seed0"]
[node.validator146]
persistent_peers = ["seed1"]
[node.validator147]
persistent_peers = ["seed2"]
[node.validator148]
persistent_peers = ["seed3"]
[node.validator149]
persistent_peers = ["seed4"]
[node.validator150]
persistent_peers = ["seed0"]
[node.validator151]
persistent_peers = ["seed1"]
[node.validator152]
persistent_peers = ["seed2"]
[node.validator153]
persistent_peers = ["seed3"]
[node.validator154]
persistent_peers = ["seed4"]
[node.validator155]
persistent_peers = ["seed0"]
[node.validator156]
persistent_peers = ["seed1"]
[node.validator157]
persistent_peers = ["seed2"]
[node.validator158]
persistent_peers = ["seed3"]
[node.validator159]
persistent_peers = ["seed4"]
[node.validator160]
persistent_peers = ["seed0"]
[node.validator161]
persistent_peers = ["seed1"]
[node.validator162]
persistent_peers = ["seed2"]
[node.validator163]
persistent_peers = ["seed3"]
[node.validator164]
persistent_peers = ["seed4"]
[node.validator165]
persistent_peers = ["seed0"]
[node.validator166]
persistent_peers = ["seed1"]
[node.validator167]
persistent_peers = ["seed2"]
[node.validator168]
persistent_peers = ["seed3"]
[node.validator169]
persistent_peers = ["seed4"]
[node.validator170]
persistent_peers = ["seed0"]
[node.validator171]
persistent_peers = ["seed1"]
[node.validator172]
persistent_peers = ["seed2"]
[node.validator173]
persistent_peers = ["seed3"]
[node.validator174]
persistent_peers = ["seed4"]
